version: '2'

services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: amazondb
      restart: always
      volumes:
        - data-volume:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    command: bash -c "./runserver.sh"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db

  backend:
    build: ./backend
    command: bash -c "./gradlew run"
    ports:
      - "9999:9999" # port for UPS
      - "8888:8888" # port for frontend
volumes:
   data-volume: 